// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwdopeclnbtrnywmojra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3ZG9wZWNsbmJ0cm55d21vanJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMTU3NTYsImV4cCI6MjA4ODc5MTc1Nn0.gDlqXEJOuGkmZrq9PX6itu90h4jbZGB76UuG6mR1Okg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});